# gruvbox  dark_plus autumn_night everblush everforest_dark
theme        = "dark_plus"

[editor]
mouse        = true
# Highlight current line
cursorline   = true
true-color   = true

[editor.cursor-shape]
insert       = "bar"
normal       = "block"
select       = "underline"
