[[language]]
name = "rust"
file-types  = ["rs"]
roots       = ["Cargo.toml", "Cargo.lock"]
auto-format = false

[language-server.rust-analyzer.config.check]
command = "clippy"

[[grammar]]
name = "rust"
